# Human and Economic Storm Damage Impact in the United States

## Synopsis

This report indentifies the most impactful weather events affecting human populations within the United States in terms of fatalities, injuries and economic losses.  The [Storm Events Database](https://www.ncdc.noaa.gov/stormevents/) complied by the National Oceanic and Atmospheric Administration (NOAA) from 1950 to 2011 will be used to answer the following questions:

* Across the United States, which types of events are most harmful with respect to population health?
* Across the United States, which types of events have the greatest economic consequences?

## Data Processing

### Required Packages

To download and read the data, we need the following packages:

```{R results='hide', message=FALSE, warning=FALSE}
install.packages("downloader", repos="http://cran.us.r-project.org")
install.packages("R.utils", , repos="http://cran.us.r-project.org")

library(downloader)
library(tools)    # md5sum
library(R.utils)  # bunzip2d
```

### Source Data

```{R}
if(!file.exists("data")){dir.create("data")}

if(!file.exists("data/repdata-data-StormData.csv")) {
  fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
  download.file(fileUrl,destfile="./data/repdata-data-StormData.csv.bz2",method="curl")
  bunzip2("data/repdata-data-StormData.csv.bz2")
}
stormDataRaw <- read.csv("data/repdata-data-StormData.csv")
```

### Dimensions and Structure of the Storm Events Data

```{R}
dim(stormDataRaw)
str(stormDataRaw)
```

### Data Cleaning

We will be using `dplyr` package for data summarystormData$eventType[grepl("thun.*orm", stormData$EVTYPE, ignore.case = TRUE)] and manipulation.

```{R results='hide', message=FALSE, warning=FALSE}
# Use dplyr
install.packages("dplyr", repos="http://cran.us.r-project.org")
library(dplyr)
```

### Subset data

First take a subset of relevant column variables:

* BGN_DATE
* EVTYPE
* FATALITIES
* INJURIES
* PROPDMG
* PROPDMGEXP
* CROPDMG
* CROPDMGEXP

```{R}
stormData <- dplyr::select(stormDataRaw, BGN_DATE, EVTYPE, FATALITIES, INJURIES, PROPDMG, PROPDMGEXP, CROPDMG, CROPDMGEXP)
```

### Date Conversion

Convert the text date to a date type.

```{R}
# Convert date
stormData$beginDate <- as.Date(strptime(stormData$BGN_DATE, format = "%m/%d/%Y %H:%M:%S"))

minDate <- stormData %>% filter(beginDate == min(beginDate))
maxDate <- stormData %>% filter(beginDate == max(beginDate))

minDate$beginDate[1]
maxDate$beginDate[1]
```

### Standardize Events

In many cases, there are multiple event types for the same meteorological event.  For example, there are 88 event types that describe thunderstorms. The following code will consolidate related event types into single event types.

```{R}
length(unique(stormData$EVTYPE[grepl("thun.*orm", stormData$EVTYPE, ignore.case = TRUE)]))

# Create another column to consolidate event types
stormData <- mutate(stormData, eventType = as.character(stormData$EVTYPE))

stormData$eventType[grepl("tornad", stormData$eventType, ignore.case = TRUE)]          <- "TORNADO"
stormData$eventType[grepl("thun.*orm", stormData$eventType, ignore.case = TRUE)]       <- "THUNDERSTORM"  
stormData$eventType[grepl("tstm", stormData$eventType, ignore.case = TRUE)]            <- "THUNDERSTORM"  
stormData$eventType[grepl("snow", stormData$eventType, ignore.case = TRUE)]            <- "SNOW"  
stormData$eventType[grepl("blizzard", stormData$eventType, ignore.case = TRUE)]        <- "BLIZZARD"  
stormData$eventType[grepl("hail", stormData$eventType, ignore.case = TRUE)]            <- "HAIL"  
stormData$eventType[grepl("rain", stormData$eventType, ignore.case = TRUE)]            <- "RAIN"  
stormData$eventType[grepl("precip", stormData$eventType, ignore.case = TRUE)]          <- "RAIN"  
stormData$eventType[grepl("hurricane", stormData$eventType, ignore.case = TRUE)]       <- "HURRICANE"  
stormData$eventType[grepl("tropical.*storm", stormData$eventType, ignore.case = TRUE)] <- "TROPICALSTORM"  
stormData$eventType[grepl("flood", stormData$eventType, ignore.case = TRUE)]           <- "FLOOD"  
stormData$eventType[grepl("fire", stormData$eventType, ignore.case = TRUE)]            <- "FIRE"  
stormData$eventType[grepl("lightn", stormData$eventType, ignore.case = TRUE)]          <- "LIGHTNING"  
stormData$eventType[grepl("wind", stormData$eventType, ignore.case = TRUE)]            <- "WIND"  
stormData$eventType[grepl("cold", stormData$eventType, ignore.case = TRUE)]            <- "COLD"  
stormData$eventType[grepl("heat", stormData$eventType, ignore.case = TRUE)]            <- "HEAT"  
stormData$eventType[grepl("storm surge", stormData$eventType, ignore.case = TRUE)]     <- "STORM SURGE"
stormData$eventType[grepl("freeze", stormData$eventType, ignore.case = TRUE)]          <- "FREEZE"
stormData$eventType[grepl("frost", stormData$eventType, ignore.case = TRUE)]          <- "FREEZE"
stormData$eventType <- as.factor(stormData$eventType)
```
## Results

### Load knitr package for table display.

```{R results='hide', message=FALSE, warning=FALSE}
install.packages("knitr", repos="http://cran.us.r-project.org")
library(knitr)
```

### Aggregate event damage

To compute human and property damage, aggregate the sums of damage from relevant columns.  For instance, total economic damage per event will combine property and crop damage aggregate sums.  Total human damage by event will be combine fatalities and injuries.

#### Compute Economic Damage

Use formattable for current formatting
```{R results='hide', message=FALSE, warning=FALSE}
install.packages("formattable", repos="http://cran.us.r-project.org")
library(formattable)
```

```{R}
# Calculate property damage amounts
PROPDMGEXP  <- levels(stormData$PROPDMGEXP)
pMultiplier <- c(1,1,1,1,1,10,100,1000,10000,100000,1000000,10000000,100000000,1000000000,100,100,1000,1000000,1000000)
propLookup  <- data.frame(cbind(PROPDMGEXP,pMultiplier))
propLookup$pMultiplier <- as.numeric(as.character(propLookup$pMultiplier))
stormData <- merge(stormData,propLookup)
stormData$totalPropDamage <- stormData$PROPDMG*stormData$pMultiplier
# Compute crop damage
CROPDMGEXP <- levels(stormData$CROPDMGEXP)
cMultiplier <- c(1,1,1,100,1000000000,1000,1000,1000000,1000000)  
cropLookup  <- data.frame(cbind(CROPDMGEXP, cMultiplier))  
cropLookup$cMultiplier <- as.numeric(as.character(cropLookup$cMultiplier))
stormData <- merge(stormData,cropLookup)
stormData$totalCropDamage <- stormData$CROPDMG*stormData$cMultiplier
stormData$totalDamage <- stormData$totalPropDamage + stormData$totalCropDamage
# generate top economic damage
topEconDamage <- stormData %>% group_by(eventType) %>% summarise(sumTotalDamage=sum(totalDamage)) %>% arrange(desc(sumTotalDamage)) %>% select(eventType,sumTotalDamage) %>% top_n(12)
topEconDamage$sumTotalDamage <- currency(topEconDamage$sumTotalDamage, symbol = "$")
```
#### Top Economic Storm Damage
```{R} 
kable(topEconDamage, col.names=c("Event","Total Property and Crop Damage"), caption = "Top 12 Economic Impact from Storm Events")
```

The table above shows the 12 top most impactful storm events in terms of economic damage.  Across the United States, floods, hurricanes, tornados are the top 3 most harmful with respect to economic consequences.

#### Compute Human Damage
```{R}
# Compute human damage
topHumanFatalities <- stormData %>% group_by(eventType) %>% summarise(sumHumanFatalities=sum(FATALITIES)) %>% arrange(desc(sumHumanFatalities))
topHumanInjuries <- stormData %>% group_by(eventType) %>% summarise(sumHumanInjuries=sum(INJURIES)) %>% arrange(desc(sumHumanInjuries))

# Combine all top damage data sets
allDamage <- merge(topEconDamage, topHumanFatalities)
allDamage <- merge(allDamage, topHumanInjuries)
allDamage$sumHumanImpact <- allDamage$sumHumanFatalities + allDamage$sumHumanInjuries

# Generate top human damage
topHumanDamage <- arrange(allDamage,desc(sumHumanImpact))  %>% select(eventType,sumHumanImpact, sumHumanFatalities, sumHumanInjuries) %>% top_n(12)
```
#### Top Human Damage
```{R}
kable(topHumanDamage, col.names=c("Event", "Human Impact", "Fatalites", "Injuries"), caption = "Top 12 Human Impact from Storm Events")
```

The table above shows the 12 top most impactful storm events on human populations in terms of fatalities and injuries.  Across the United States, tornado, thunderstorm and flood events are most harmful with respect to population health.

### Data Visualization

#### Required Packages

```{R results='hide', message=FALSE, warning=FALSE}
install.packages("ggplot2", repos="http://cran.us.r-project.org")
library(ggplot2)
```

Show total damage as 2d scatter plot with total economic damage as x-axis, total human impact as y-axis and fatalities as point size.

```{R message=FALSE, fig.fullwidth=TRUE, fig.width=8, fig.height=8}

topDamage <- allDamage[1:12,]

div = 1000000000
ggplot(topDamage, aes(x=sumTotalDamage/div, y=sumHumanImpact, color=eventType)) +  
    geom_point(aes(size = sumHumanFatalities)) +
    labs(size="Fatalities") +
    geom_text(data = topDamage[topDamage$eventType=="TORNADO" ,], 
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.8, vjust = 1.1) +
    geom_text(data = topDamage[topDamage$eventType=="HEAT" ,], 
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = 1.5) +
    geom_text(data = topDamage[topDamage$eventType=="FLOOD" ,], 
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = 1.5) +
    geom_text(data = topDamage[topDamage$eventType=="LIGHTNING" ,], 
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.3, vjust = .5) +
    geom_text(data = topDamage[topDamage$eventType=="THUNDERSTORM" ,], 
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.2, vjust = .5) +
    geom_text(data = topDamage[topDamage$eventType=="HURRICANE" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.2, vjust = .5) +
    geom_text(data = topDamage[topDamage$eventType=="WIND" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.5, vjust = -.5) +
    geom_text(data = topDamage[topDamage$eventType=="RIP CURRENT" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = 1, vjust = -1) +
    geom_text(data = topDamage[topDamage$eventType=="AVALANCHE" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), vjust = -.3) +
    geom_text(data = topDamage[topDamage$eventType=="COLD" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = .5, vjust = -1) +
    geom_text(data = topDamage[topDamage$eventType=="WINTER STORM" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.1, vjust = 2) +
    scale_colour_brewer(palette="Paired")   +
    scale_size_area(max_size=30) +
    scale_x_continuous(labels = scales::dollar, limits = c(min(topDamage$sumTotalDamage)/div,
                                                         max(topDamage$sumTotalDamage)/div))  +
    scale_y_continuous(labels = scales::comma, limits = c(min(topDamage$sumHumanImpact),
                                                          max(topDamage$sumHumanImpact)+5000)) +
    xlab("Economic Impact (billion)") +
    ylab("Human Impact (deaths and injuries)") +
    theme(panel.background = element_rect(fill = "black")) +
    ggtitle("Most Impactful Human and\nEconomic Damage from Storms")
```
The graph above shows the magnitude of harm to human life that comes from tornados with moderate economic damage.  Tornados are far and away the most dangerous for human safety.  Where as floods produce the most economic damage and relatively moderate human impact. Hurricanes produce the second most impactful economic damage and less human harm than thunderstorms and wind.


To better understand economic damage less than $100 billion and 12,500 human lives affected, zoom into storm data to focus on these events.

```{R message=FALSE, fig.fullwidth=TRUE, fig.width=8, fig.height=8}
div = 1000000000
ggplot(topDamage, aes(x=sumTotalDamage/div, y=sumHumanImpact, color=eventType)) +  
    geom_point(aes(size = sumHumanFatalities)) +
    labs(size="Fatalities") +
    geom_text(data = topDamage[topDamage$eventType=="THUNDERSTORM" ,], 
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.2, vjust = .5) +
    geom_text(data = topDamage[topDamage$eventType=="WIND" ,], 
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.5, vjust = .5) +
    geom_text(data = topDamage[topDamage$eventType=="ICE STORM" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.2, vjust = .5) +
    geom_text(data = topDamage[topDamage$eventType=="COLD" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = .5, vjust = -1) +
    geom_text(data = topDamage[topDamage$eventType=="FIRE" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.4, vjust = .5) +
    geom_text(data = topDamage[topDamage$eventType=="WINTER STORM" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.1, vjust = 1.1) +
    geom_text(data = topDamage[topDamage$eventType=="HAIL" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = .5, vjust = -1) +
    geom_text(data = topDamage[topDamage$eventType=="TROPICALSTORM" ,],
              aes(sumTotalDamage/div,sumHumanImpact, label = eventType), hjust = -.2, vjust = .5) +
    scale_colour_brewer(palette="Paired")   +
    scale_size_area(max_size=30) +
    scale_x_continuous(labels = scales::dollar, limits = c(min(topDamage$sumTotalDamage)/div,
                                                         max(30)))  +
    scale_y_continuous(labels = scales::comma, limits = c(min(topDamage$sumHumanImpact),
                                                          max(12000))) +
    xlab("Economic Impact (billion)") +
    ylab("Human Impact (deaths and injuries)") +
    theme(panel.background = element_rect(fill = "black")) +
    ggtitle("Most Impactful Human and\nEconomic Damage from Storms (detail)")
```


The graph above is a zoomed in view to focus on storm events clustered under 12,500 human impact and less than $30 billion dollars.

Being able to see this data more clearly after zooming in, an insight that I personally gained from this graph was that indeed, as the Talking Heads sang, ["air can hurt you too"](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwjC5djo4onSAhVkwlQKHVQCBMQQtwIIJzAC&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DQ9kqoD1t4lw&usg=AFQjCNGjak7SD0Mq4IuLh0sbewFPSLpbow&sig2=u4HZ5NVPVMl-vvKpSBcjUQ).  In this case wind is pretty effective at killing you.

## References

[coursera: Reproducible Research by John Hopkins University Bloomberg School of Public Health](https://www.coursera.org/learn/reproducible-research) Roger D. Peng, PhD, Associate Professor, Biostatistics, Jeff Leek, PhD, Associate Professor, Biostatistics, and Brian Caffo, PhD, Professor, Biostatistics.

[Storm Events Database](https://www.ncdc.noaa.gov/stormevents/) National Oceanic and Atmospheric Administration.  United States Department of Commerce.

[Read Headed Step Data blog by Keith Helfrich](http://redheadedstepdata.io) Data visualization ideas.

[knitr](https://yihui.name/knitr/) Yihui Xie

[Fear of Music by Talking Heads](https://en.wikipedia.org/wiki/Fear_of_Music) Sire Records 1979

<br><br>
